name: Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Build SDist
        run: uv build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            macos-15-intel,
            macos-26,
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        with:
          extras: "uv"

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/crosci
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
